(function(){
const params=new URLSearchParams(location.search);
let view=params.get('view')||(page==='activity'?'list':'home');
let keyword=params.get('keyword')||'',year=params.get('year')||'',month=params.get('month')||'',activityType=params.get('activityType')||'',activityTab=params.get('activityTab')||'basic';
let selectedActivityId=params.get('activityId')||'medal-2',picker='',weekToast='';
const activityTypes=['行政素质能力大赛','求职训练营','基层帮扶','职业沙龙','职业规划大赛','简历大赛','勋章设计大赛','就业创业大赛','职业规材料书','训练营','选调生','生涯活动体验周'];
const activities=[
{id:'medal-2',title:'第二届勋章设计大赛',time:'2026-06-16 00:00',place:'',cover:'blue',type:'勋章设计大赛',status:'已结束'},
{id:'medal',title:'勋章设计大赛',time:'2026-04-01 00:00',place:'',cover:'empty',type:'勋章设计大赛',status:'已结束'},
{id:'plan-score',title:'生涯规划书上传并评分',time:'2026-04-01 00:00',place:'',cover:'blue',type:'职业规划大赛',status:'已结束'},
{id:'salon',title:'职业沙龙',time:'2026-03-19 00:00',place:'湖南省长沙市天心区芙蓉南路二段390号悦动商业广场B座606号',cover:'empty',type:'职业沙龙',status:'已结束'},
{id:'series',title:'生涯活动功能系列',time:'2026-03-03 09:00',place:'',cover:'empty',type:'生涯活动体验周',status:'已结束',series:true},
{id:'test',title:'生涯活动功能测试',time:'2026-03-03 00:00',place:'就业之家',cover:'pink',type:'训练营',status:'已结束'},
{id:'resume-copy',title:'简历大赛_副本',time:'2026-02-03 00:00',place:'',cover:'blue',type:'简历大赛',status:'已结束'},
{id:'resume',title:'简历大赛',time:'2025-12-01 00:00',place:'',cover:'blue',type:'简历大赛',status:'已结束'},
{id:'yunyan',title:'云研科技生涯活动大赛',time:'2025-11-15 15:15',place:'',cover:'blue',type:'就业创业大赛',status:'已结束'}
];
function pcHead(title,desc,action=''){return `<div class="page-head activity-week-head"><div><h1>${title}</h1><p>${desc}</p></div>${action}</div>`}
function selectedActivity(){return activities.find(x=>x.id===selectedActivityId)||activities[0]}
function filteredActivities(){if(view==='mine')return [];return activities.filter(x=>(!keyword||x.title.includes(keyword))&&(!year||x.time.startsWith(year))&&(!month||x.time.slice(5,7)===month)&&(!activityType||x.type===activityType))}
function cover(x){return `<span class="activity-cover ${x.cover}">${x.series?'<em>系列</em>':''}${x.cover==='empty'?'<i>▧</i>':''}</span>`}
function activityList(){const rows=filteredActivities();return pcHead('生涯活动','查看学校现有生涯活动，支持按时间、类型和我的活动筛选。')+`<section class="activity-pc-panel"><div class="activity-toolbar"><label class="activity-search"><span>⌕</span><input value="${keyword}" data-activity-search placeholder="搜索活动名称"></label><button class="activity-filter ${year||month?'active':''}" data-activity-picker="time">${year||month?`${year||'年份'} ${month?month+'月':''}`:'时间'} <i>⌄</i></button><button class="activity-filter ${activityType?'active':''}" data-activity-picker="type">${activityType||'活动类型'} <i>⌄</i></button><button class="mine-activity ${view==='mine'?'active':''}" data-activity-mine>我的活动</button></div>${rows.length?`<div class="activity-full-list">${rows.map(x=>`<button class="activity-list-row" data-activity-detail="${x.id}">${cover(x)}<span class="activity-row-copy"><b>${x.title}</b><small>时间：${x.time}</small><small title="${x.place}">地点：${x.place}</small></span><span class="activity-status">${x.status}</span><i>›</i></button>`).join('')}</div>`:`<div class="activity-empty"><span>▧</span><p>暂无数据</p></div>`}</section>${pickerView()}`}
function pickerView(){if(!picker)return '';if(picker==='time'){const years=Array.from({length:17},(_,i)=>String(2020+i)),months=Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0'));return `<div class="activity-picker-mask"><section class="activity-picker-card"><header><button data-activity-clear>清空</button><b>选择年月</b><button data-activity-confirm>确认</button></header><div class="time-picker-pc"><div>${years.map(x=>`<button class="${year===x?'chosen':''}" data-activity-year="${x}">${x}</button>`).join('')}</div><div>${months.map(x=>`<button class="${month===x?'chosen':''}" data-activity-month="${x}">${x}月</button>`).join('')}</div></div></section></div>`}return `<div class="activity-picker-mask"><section class="activity-picker-card type"><header><button data-activity-clear>清空</button><b>活动类型</b><button data-activity-confirm>确认</button></header><div class="activity-type-grid">${activityTypes.map(x=>`<button class="${activityType===x?'chosen':''}" data-activity-type="${x}">${x}</button>`).join('')}</div></section></div>`}
function activityDetail(){const x=selectedActivity();const tabs=[['gallery','往期锦集'],['basic','基础信息'],['apply','报名与签到']];let body=activityTab==='basic'?`<section class="activity-detail-section"><h2>${x.title}</h2><dl><div><dt>活动时间：</dt><dd>2026-06-16 00:00至2026-07-31 00:00</dd></div></dl><h3>勋章信息</h3><p><b>勋章类型：</b>探索勋章</p><p><b>勋章数量：</b>1</p><h3>活动介绍</h3><p>${x.title}</p></section>`:activityTab==='gallery'?`<section class="activity-detail-section gallery"><div class="activity-gallery-cover blue"></div><p>${x.title}</p></section>`:`<section class="activity-detail-section activity-empty"><span>▧</span><p>暂无数据</p></section>`;return pcHead('生涯活动详情',x.title,`<button data-activity-back>返回活动列表</button>`)+`<section class="activity-detail-shell"><div class="activity-detail-banner blue">${cover(x)}<b>${x.title}</b></div><nav class="activity-detail-tabs">${tabs.map(([id,n])=>`<button class="${activityTab===id?'active':''}" data-activity-tab="${id}">${n}</button>`).join('')}</nav>${body}</section>`}
function weekHome(){return pcHead('生涯体验周','查看当前体验周活动并进入原有报名与闯关流程。')+`<section class="week-pc-shell"><div class="week-overview"><div class="week-round-cover"><span></span></div><div><h2>测试活动</h2><dl><div><dt>时　间：</dt><dd>2026-06-01 00:00</dd></div><div><dt>地　点：</dt><dd>长沙总部基地</dd></div><div><dt>主办方：</dt><dd></dd></div></dl></div></div><div class="week-detail"><h2>活动详情</h2><p>测试内容</p></div><button class="week-apply" data-week-view="challenge">报名生涯体验周 <span>›</span></button></section>`}
function weekChallenge(){return pcHead('生涯体验周','查看体验周闯关进度与关卡状态。',`<button data-week-view="home">返回活动详情</button>`)+`<section class="week-challenge-shell"><div class="week-progress"><p>当前已闯过 <b>0/1</b> 个关卡，已超过本年级 <b>0.00%</b> 人</p><i><em></em></i></div><div class="week-stage-head"><span></span><h2>一阶段</h2></div><button class="week-level" data-week-level><span class="week-flag">⚑</span><span class="week-level-copy"><b>第一关</b><small>0人已闯关</small></span><span class="week-lock">▣</span><i>›</i></button></section>${weekToast?`<div class="week-toast">${weekToast}</div>`:''}`}
function featurePage(){return page==='activity'?(view==='detail'?activityDetail():activityList()):(view==='challenge'?weekChallenge():weekHome())}
function setView(next){view=next;const u=new URL(location.href);u.searchParams.set('page',page);u.searchParams.set('view',view);history.pushState(null,'',u);render();scrollTo(0,0)}
const oldSimple=simple;simple=function(){return page==='activity'||page==='week'?featurePage():oldSimple()};
const oldSync=syncUrl;syncUrl=function(){oldSync();const u=new URL(location.href);if(page==='activity'){u.searchParams.set('view',view);if(view==='detail')u.searchParams.set('activityId',selectedActivityId);else u.searchParams.delete('activityId');[['keyword',keyword],['year',year],['month',month],['activityType',activityType]].forEach(([k,v])=>v?u.searchParams.set(k,v):u.searchParams.delete(k));if(view==='detail')u.searchParams.set('activityTab',activityTab);else u.searchParams.delete('activityTab')}else if(page==='week'){u.searchParams.set('view',view);['activityId','activityTab','keyword','year','month','activityType'].forEach(k=>u.searchParams.delete(k))}else{['view','activityId','activityTab','keyword','year','month','activityType'].forEach(k=>u.searchParams.delete(k))}history.replaceState(null,'',u)};
const oldBind=bind;bind=function(){oldBind();document.querySelectorAll('[data-page="activity"]').forEach(x=>x.onclick=()=>{page='activity';view='list';render();scrollTo(0,0)});document.querySelectorAll('[data-page="week"]').forEach(x=>x.onclick=()=>{page='week';view='home';render();scrollTo(0,0)});document.querySelectorAll('[data-activity-search]').forEach(x=>x.oninput=()=>{keyword=x.value;view='list';render();const q=document.querySelector('[data-activity-search]');if(q){q.focus();q.setSelectionRange(q.value.length,q.value.length)}});document.querySelectorAll('[data-activity-picker]').forEach(x=>x.onclick=()=>{picker=x.dataset.activityPicker;render()});document.querySelectorAll('[data-activity-confirm]').forEach(x=>x.onclick=()=>{picker='';view='list';render()});document.querySelectorAll('[data-activity-clear]').forEach(x=>x.onclick=()=>{if(picker==='time'){year='';month=''}else activityType='';render()});document.querySelectorAll('[data-activity-year]').forEach(x=>x.onclick=()=>{year=x.dataset.activityYear;render()});document.querySelectorAll('[data-activity-month]').forEach(x=>x.onclick=()=>{month=x.dataset.activityMonth;render()});document.querySelectorAll('[data-activity-type]').forEach(x=>x.onclick=()=>{activityType=x.dataset.activityType;render()});document.querySelectorAll('[data-activity-mine]').forEach(x=>x.onclick=()=>setView(view==='mine'?'list':'mine'));document.querySelectorAll('[data-activity-detail]').forEach(x=>x.onclick=()=>{selectedActivityId=x.dataset.activityDetail;activityTab='basic';setView('detail')});document.querySelectorAll('[data-activity-back]').forEach(x=>x.onclick=()=>setView('list'));document.querySelectorAll('[data-activity-tab]').forEach(x=>x.onclick=()=>{activityTab=x.dataset.activityTab;render()});document.querySelectorAll('[data-week-view]').forEach(x=>x.onclick=()=>setView(x.dataset.weekView));document.querySelectorAll('[data-week-level]').forEach(x=>x.onclick=()=>{weekToast='当前活动已经结束，无法闯关签到';render();setTimeout(()=>{weekToast='';render()},3500)})};
window.addEventListener('popstate',()=>{const p=new URLSearchParams(location.search);page=p.get('page')||'home';view=p.get('view')||(page==='activity'?'list':'home');selectedActivityId=p.get('activityId')||selectedActivityId;activityTab=p.get('activityTab')||'basic';keyword=p.get('keyword')||'';year=p.get('year')||'';month=p.get('month')||'';activityType=p.get('activityType')||'';render()});
render();
})();
