state.aiCareerHome=window.AICareerHomeState;
let planView=new URLSearchParams(location.search).get('view')||'home';
const aiHomeDemoState=new URLSearchParams(location.search).get('aiState');
if(aiHomeDemoState==='unentitled')state.aiCareerHome.entitled=false;
if(aiHomeDemoState==='empty')state.aiCareerHome.planStatus='empty';
if(aiHomeDemoState==='error')state.aiCareerHome.planStatus='error';
if(aiHomeDemoState==='no-change')state.aiCareerHome.hasImportantChange=false;
if(aiHomeDemoState==='portrait-unentitled')state.aiCareerHome.portraitEntitled=false;
if(aiHomeDemoState==='portrait-empty')state.aiCareerHome.portraitStatus='empty';
if(aiHomeDemoState==='portrait-error')state.aiCareerHome.portraitStatus='error';
if(aiHomeDemoState==='both-unentitled'){state.aiCareerHome.portraitEntitled=false;state.aiCareerHome.entitled=false}

function legacyHomePanels(){return `<div class="dashboard-grid"><section class="content-panel"><h2>推荐学习</h2><div class="data-list">${state.courses.map(x=>`<article data-page="${x.page}"><span class="org-logo ${x.page}">${x.title[0]}</span><div><h3>${x.title}<em>${x.type}</em></h3><p>${x.meta}</p></div><div class="row-action"><button>${x.progress?'继续学习':'查看详情'}</button></div></article>`).join('')}</div></section><aside class="todo-panel"><div class="panel-head"><h2>生涯服务待办</h2><button>全部 →</button></div>${state.todos.map(x=>`<article data-page="${x.page}"><span class="todo-icon">${svg('check')}</span><div><h3>${x.title}</h3><p>${x.note}</p></div><em class="status-pill">${x.status}</em></article>`).join('')}</aside></div>`}

function homePortraitRadar(){const dims=state.careerArchive.dimensions||[],cx=108,cy=88,r=59,a=dims.map((_,i)=>-Math.PI/2+i*Math.PI/3),pt=(q,i)=>`${cx+Math.cos(a[i])*q},${cy+Math.sin(a[i])*q}`;return `<svg class="home-portrait-radar" viewBox="0 0 216 176" role="img" aria-label="能力画像概览"><g class="radar-grid">${[1,.66,.33].map(k=>`<polygon points="${a.map((_,i)=>pt(r*k,i)).join(' ')}"/>`).join('')}${a.map((_,i)=>{const p=pt(r,i).split(',');return `<line x1="${cx}" y1="${cy}" x2="${p[0]}" y2="${p[1]}"/>`}).join('')}</g><polygon class="radar-value" points="${dims.map((x,i)=>pt(r*(x.value||0)/100,i)).join(' ')}"/>${dims.map((x,i)=>{const p=pt(r*(x.value||0)/100,i).split(',');return `<circle cx="${p[0]}" cy="${p[1]}" r="3"/>`}).join('')}</svg>`}

function homePortraitPanel(){const h=state.aiCareerHome;if(!h.portraitEntitled)return `<section class="home-portrait-panel portrait-fallback"><div class="compact-head"><div><span class="panel-eyebrow">我的生涯状态</span><h2>职业探索期</h2></div><span class="soft-badge">成长档案 ${state.stats.find(x=>x.label==='成长档案')?.value||0} 条</span></div><div class="portrait-fallback-body"><span class="icon-box green">${svg('doc')}</span><div><h3>生涯数据持续积累中</h3><p>查看现有测评、课程、活动与AI应用形成的正式成长记录。</p></div></div><button class="text-action" data-page="archive">查看成长档案</button></section>`;if(h.portraitStatus==='empty')return `<section class="home-portrait-panel portrait-fallback"><div class="compact-head"><div><span class="panel-eyebrow">我的生涯画像</span><h2>画像尚未生成</h2></div></div><div class="portrait-fallback-body"><span class="icon-box green">${svg('check')}</span><div><h3>完成现有职业测评</h3><p>测评完成后，这里将同步展示后台正式能力画像概览。</p></div></div><button class="primary" data-page="assessment">去完成职业测评</button></section>`;if(h.portraitStatus==='error')return `<section class="home-portrait-panel portrait-fallback"><div class="compact-head"><div><span class="panel-eyebrow">我的生涯画像</span><h2>画像暂时无法加载</h2></div></div><p class="muted-copy">其他首页内容不受影响，可稍后进入能力画像页面重新查看。</p><button class="text-action" data-page="portrait">进入能力画像</button></section>`;const dims=state.careerArchive.dimensions||[],best=dims.reduce((a,b)=>a.value>b.value?a:b,dims[0]),weak=dims.reduce((a,b)=>a.value<b.value?a:b,dims[0]);return `<section class="home-portrait-panel"><div class="compact-head"><div><span class="panel-eyebrow">我的生涯画像</span><h2>能力画像概览</h2></div><span class="soft-badge">画像更新时间 ${h.portraitUpdatedAt}</span></div><div class="portrait-summary"><button class="radar-button" data-page="portrait">${homePortraitRadar()}</button><div class="portrait-facts"><div><small>能力关键词</small><p class="keyword-list">${state.careerArchive.keywords.slice(0,3).map(x=>`<span>${x}</span>`).join('')}</p></div><dl><div><dt>当前优势维度</dt><dd>${best.name}</dd></div><div><dt>当前待提升维度</dt><dd>${weak.name}</dd></div></dl></div></div><button class="text-action" data-page="portrait">查看完整画像 ›</button></section>`}

function homePlanPanel(){const h=state.aiCareerHome;if(!h.entitled)return `<section class="home-plan-panel current-plan-panel"><div class="compact-head"><div><span class="panel-eyebrow">推荐学习</span><h2>适合当前阶段的内容</h2></div></div>${state.courses.slice(0,2).map(x=>`<button class="compact-service" data-page="${x.page}"><span class="org-logo ${x.page}">${x.title[0]}</span><span><b>${x.title}</b><small>${x.meta}</small></span><i>›</i></button>`).join('')}</section>`;if(h.planStatus==='ready'){}else if(h.planStatus==='empty')return `<section class="home-plan-panel current-plan-panel plan-empty"><div class="compact-head"><div><span class="panel-eyebrow">当前主规划</span><h2>生成你的AI生涯规划书</h2></div></div><div class="plan-empty-body"><span class="icon-box green">${svg('doc')}</span><p>基于已有测评、画像、学习和实践记录，形成探索型阶段规划。</p></div><button class="primary" data-plan-view="generate">生成规划书</button></section>`;if(h.planStatus==='error')return `<section class="home-plan-panel current-plan-panel plan-empty"><div class="compact-head"><div><span class="panel-eyebrow">当前主规划</span><h2>规划暂时无法加载</h2></div></div><p class="muted-copy">画像与成长记录仍可正常查看，可稍后重试规划模块。</p><button class="text-action" data-page="plan">进入AI生涯规划</button></section>`;const p=h.mainPlan;return `<section class="home-plan-panel current-plan-panel"><div class="compact-head"><div><span class="panel-eyebrow">当前主规划</span><h2>${p.name}</h2></div><div class="plan-badges"><span>${p.planType}</span><span>${p.currentVersion}</span></div></div><div class="compact-plan-focus"><small>本阶段成长重点</small><h3>${p.stageFocus}</h3><p>当前生涯阶段：${p.careerStage}</p></div><dl class="compact-plan-meta"><div><dt>建议优先关注</dt><dd>${p.priorityStage}</dd></div><div><dt>最近更新</dt><dd>${p.updatedAt}</dd></div></dl><div class="plan-actions"><button class="primary" data-plan-view="report">查看规划书</button><button data-plan-view="versions">查看版本记录</button></div></section>`}

function homeNextPanel(){const h=state.aiCareerHome;if(h.hasImportantChange&&h.affectedSections.length){const x=h.affectedSections[0];return `<aside class="home-next-panel growth-next-panel"><div class="compact-head"><div><span class="panel-eyebrow orange">成长变化与下一步</span><h2>成长数据有新变化</h2></div><span class="change-mark">更新</span></div><article class="change-card"><span class="todo-icon">${svg('check')}</span><div><h3>${x.title}</h3><p>${x.reason}</p><small>${x.scope}</small></div></article><button class="next-main-action" data-plan-view="update">查看变化</button><div class="related-service-list"><h3>关联现有服务</h3>${h.relatedExistingServices.slice(0,2).map(x=>`<button data-page="${x.page}"><b>${x.title}</b><small>${x.note}</small><i>›</i></button>`).join('')}</div></aside>`}return `<aside class="home-next-panel growth-next-panel"><div class="compact-head"><div><span class="panel-eyebrow">成长变化与下一步</span><h2>当前规划暂无重要变化</h2></div></div><div class="related-service-list no-change"><h3>关联现有服务</h3>${h.relatedExistingServices.slice(0,3).map(x=>`<button data-page="${x.page}"><b>${x.title}</b><small>${x.note}</small><i>›</i></button>`).join('')}</div></aside>`}

function archiveRecordPage(x){return ({'职业测评':'assessment','线上课':'course','生涯活动':'activity','AI生涯规划':'plan','微视频':'video','生涯体验周':'week'})[x.source]||'archive'}
function recentArchivePanel(){const records=[...state.careerArchive.archiveRecords].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);return `<section class="recent-archive-panel"><div class="panel-head"><div><h2>近期成长记录</h2><p>来自后台正式成长档案</p></div><button data-page="archive">查看全部成长档案 →</button></div><div class="recent-record-grid">${records.map(x=>`<article data-page="${archiveRecordPage(x)}"><time>${x.date}</time><div><p><span>${x.type}</span><em>${x.status}</em></p><h3>${x.detail}</h3></div><i>›</i></article>`).join('')}</div></section>`}
function homePortraitRadar(){const dims=state.careerArchive.dimensions||[],cx=160,cy=112,r=76,a=dims.map((_,i)=>-Math.PI/2+i*Math.PI/3),pt=(q,i)=>`${cx+Math.cos(a[i])*q},${cy+Math.sin(a[i])*q}`,labelPt=i=>{const p=pt(r+31,i).split(',');return {x:p[0],y:p[1],anchor:i===0||i===3?'middle':i<3?'start':'end'}};return `<div class="home-radar-wrap"><svg class="home-portrait-radar" viewBox="0 0 320 224" role="img" aria-label="能力画像概览"><g class="radar-grid">${[1,.75,.5,.25].map(k=>`<polygon points="${a.map((_,i)=>pt(r*k,i)).join(' ')}"/>`).join('')}${a.map((_,i)=>{const p=pt(r,i).split(',');return `<line x1="${cx}" y1="${cy}" x2="${p[0]}" y2="${p[1]}"/>`}).join('')}</g><polygon class="radar-value" points="${dims.map((x,i)=>pt(r*(x.value||0)/100,i)).join(' ')}"/>${dims.map((x,i)=>{const p=pt(r*(x.value||0)/100,i).split(',');return `<circle cx="${p[0]}" cy="${p[1]}" r="3.5"/>`}).join('')}<g class="home-radar-labels">${dims.map((x,i)=>{const p=labelPt(i);return `<text class="dimension-label" x="${p.x}" y="${p.y}" text-anchor="${p.anchor}">${x.name}</text>`}).join('')}</g></svg></div>`}

function homePlanPanel(){const h=state.aiCareerHome;if(!h.entitled)return `<section class="home-plan-panel current-plan-panel"><div class="compact-head"><div><span class="panel-eyebrow">推荐学习</span><h2>适合当前阶段的内容</h2></div></div>${state.courses.slice(0,2).map(x=>`<button class="compact-service" data-page="${x.page}"><span class="org-logo ${x.page}">${x.title[0]}</span><span><b>${x.title}</b><small>${x.meta}</small></span><i>›</i></button>`).join('')}</section>`;if(h.planStatus==='empty')return `<section class="home-plan-panel current-plan-panel plan-empty"><div class="compact-head"><div><span class="panel-eyebrow">当前主规划</span><h2>生成你的AI生涯规划书</h2></div></div><div class="plan-empty-body"><span class="icon-box green">${svg('doc')}</span><p>基于已有测评、画像、学习和实践记录，形成探索型阶段规划。</p></div><button class="primary" data-plan-view="generate">生成规划书</button></section>`;if(h.planStatus==='error')return `<section class="home-plan-panel current-plan-panel plan-empty"><div class="compact-head"><div><span class="panel-eyebrow">当前主规划</span><h2>规划暂时无法加载</h2></div></div><p class="muted-copy">画像与成长记录仍可正常查看，可稍后重试规划模块。</p><button class="text-action" data-page="plan">进入AI生涯规划</button></section>`;const p=h.mainPlan;return `<section class="home-plan-panel current-plan-panel"><div class="compact-head plan-title-head"><div><span class="panel-eyebrow">当前主规划</span><h2>${p.name}</h2></div><div class="plan-badges"><span>${p.planType}</span><span>${p.currentVersion}</span></div></div><div class="compact-plan-focus"><small>本阶段成长重点</small><h3>${p.stageFocus}</h3></div><div class="plan-stage-path"><span><small>当前</small><b>${p.careerStage}</b></span><i>→</i><span><small>优先关注</small><b>${p.priorityStage.replace(/^第2阶段 · /,'')}</b></span></div><div class="plan-footer"><small>最近更新 ${p.updatedAt}</small><div class="plan-actions"><button class="primary" data-plan-view="report">查看规划书</button><button data-plan-view="versions">查看版本记录</button></div></div></section>`}

function recentArchivePanel(){const records=[...state.careerArchive.archiveRecords].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);return `<section class="recent-archive-panel"><div class="panel-head"><div><h2>近期成长记录</h2><p>来自后台正式成长档案</p></div><button data-page="archive">查看全部成长档案 →</button></div><div class="recent-archive-timeline"><div class="archive-track"></div>${records.map((x,i)=>`<article class="${i===0?'is-latest':''}" data-page="${archiveRecordPage(x)}"><span class="timeline-dot"></span><time>${x.date}</time><p><span>${x.type}</span><em>${x.status}</em></p><h3>${x.detail}</h3><button>查看详情 ›</button></article>`).join('')}</div></section>`}

function planChangeInline(){const h=state.aiCareerHome;if(h.hasImportantChange&&h.affectedSections.length){const x=h.affectedSections[0];return `<div class="plan-change-inline"><span class="todo-icon">${svg('check')}</span><div><small>成长数据有新变化</small><b>${x.title}</b><p>${x.reason}</p><em>${x.scope}</em></div><button data-plan-view="update">查看变化</button></div>`}return `<div class="plan-change-inline no-change"><span class="todo-icon">${svg('check')}</span><div><small>成长数据与规划</small><b>当前规划暂无重要变化</b></div></div>`}

function planRelatedServices(){return `<div class="plan-related-services">${state.aiCareerHome.relatedExistingServices.slice(0,2).map(x=>`<button data-page="${x.page}"><span><small>关联现有服务</small><b>${x.title}</b></span><i>›</i></button>`).join('')}</div>`}

function homePlanPanel(){const h=state.aiCareerHome;if(!h.entitled)return `<section class="home-plan-panel current-plan-panel"><div class="compact-head"><div><span class="panel-eyebrow">推荐学习</span><h2>适合当前阶段的内容</h2></div></div>${state.courses.slice(0,2).map(x=>`<button class="compact-service" data-page="${x.page}"><span class="org-logo ${x.page}">${x.title[0]}</span><span><b>${x.title}</b><small>${x.meta}</small></span><i>›</i></button>`).join('')}</section>`;if(h.planStatus==='empty')return `<section class="home-plan-panel current-plan-panel plan-empty"><div class="compact-head"><div><span class="panel-eyebrow">当前主规划</span><h2>生成你的AI生涯规划书</h2></div></div><div class="plan-empty-body"><span class="icon-box green">${svg('doc')}</span><p>基于已有测评、画像、学习和实践记录，形成探索型阶段规划。</p></div><button class="primary" data-plan-view="generate">生成规划书</button></section>`;if(h.planStatus==='error')return `<section class="home-plan-panel current-plan-panel plan-empty"><div class="compact-head"><div><span class="panel-eyebrow">当前主规划</span><h2>规划暂时无法加载</h2></div></div><p class="muted-copy">画像与成长记录仍可正常查看，可稍后重试规划模块。</p><button class="text-action" data-page="plan">进入AI生涯规划</button></section>`;const p=h.mainPlan;return `<section class="home-plan-panel current-plan-panel"><div class="compact-head plan-title-head"><div><span class="panel-eyebrow">当前主规划</span><h2>${p.name}</h2></div><div class="plan-badges"><span>${p.planType}</span><span>${p.currentVersion}</span></div></div><div class="plan-main-grid"><div><div class="compact-plan-focus"><small>本阶段成长重点</small><h3>${p.stageFocus}</h3></div><div class="plan-stage-path"><span><small>当前</small><b>${p.careerStage}</b></span><i>→</i><span><small>优先关注</small><b>${p.priorityStage.replace(/^第2阶段 · /,'')}</b></span></div></div>${planChangeInline()}</div>${planRelatedServices()}<div class="plan-footer"><small>最近更新 ${p.updatedAt}</small><div class="plan-actions"><button class="primary" data-plan-view="report">查看规划书</button><button data-plan-view="versions">查看版本记录</button></div></div></section>`}

function recentArchivePanel(){const records=[...state.careerArchive.archiveRecords].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);return `<section class="recent-archive-panel recent-archive-list"><div class="panel-head"><div><h2>近期成长记录</h2><p>来自后台正式成长档案</p></div><button data-page="archive">查看全部成长档案 →</button></div><div class="archive-record-list">${records.map(x=>`<article class="archive-record-row" data-page="${archiveRecordPage(x)}"><time>${x.date}</time><span class="record-source">${x.source}</span><div><h3>${x.name}</h3><p>${x.detail}</p></div><em>${x.status}</em><button>查看详情 ›</button></article>`).join('')}</div></section>`}

function portraitPlanWorkbench(){return `<div class="portrait-plan-primary">${homePortraitPanel()}${homePlanPanel()}</div>${recentArchivePanel()}`}

const originalHome=home;
home=function(){const top=originalHome().replace(/<div class="dashboard-grid">[\s\S]*$/,'');const h=state.aiCareerHome;return top+(!h.portraitEntitled&&!h.entitled?legacyHomePanels():portraitPlanWorkbench())};
function aiPlanPage(){const views={report:['当前规划书','查看规划摘要、能力画像、方向分析、阶段目标和学习资源建议。'],versions:['版本记录','查看当前版本及成长数据更新形成的历史版本。'],update:['成长数据更新','查看哪些规划内容受到新成长数据影响，再进入现有规划更新流程。'],generate:['生成新的规划书','进入探索型、方向型或岗位型规划书的现有生成流程。'],home:['AI生涯规划','查看当前主规划、其他规划和版本记录。']},v=views[planView]||views.home;return pageHead(v[0],v[1])+`<section class="content-panel ai-plan-entry-page"><span class="icon-box green">${svg('doc')}</span><h2>${v[0]}</h2><p>${v[1]}</p><button class="primary" data-existing="${v[0]}">进入现有${v[0]}页面</button></section>`}
const originalSimple=simple;simple=function(){return page==='plan'?aiPlanPage():originalSimple()};
const originalSyncUrl=syncUrl;syncUrl=function(){originalSyncUrl();const u=new URL(location.href);if(page==='plan')u.searchParams.set('view',planView);else u.searchParams.delete('view');history.replaceState(null,'',u)};
const originalBind=bind;bind=function(){originalBind();document.querySelectorAll('[data-plan-view]').forEach(x=>x.onclick=()=>{planView=x.dataset.planView;page='plan';render();scrollTo(0,0)})};
render();
