(function(){
const params=new URLSearchParams(location.search);let view=params.get('view')||'home',planType=params.get('planType')||'exploration',version=params.get('version')||'V1.2',feedback='',correctionChoice='',generated=false;
const types={exploration:{name:'探索型规划书',tip:'尚未明确方向',desc:'围绕专业相关方向持续探索，不要求确认岗位或发展路径。'},direction:{name:'方向型规划书',tip:'已有职业方向',desc:'先确认发展路径，再比较对应方向与准备重点。'},job:{name:'岗位型规划书',tip:'已有具体岗位',desc:'确认唯一目标岗位，围绕岗位要求形成准备建议。'}};
const chapters=['规划摘要','学生能力画像','职业倾向分析','职业发展方向分析','职业发展阶段目标','学业提升规划','实践经历规划','能力短板与提升建议','学习资源推荐'];
const stages=['入门探索与自我认知','专业认知与方向探索','能力积累与实践体验','方向聚焦与岗位准备','岗位实习与发展准备','发展落实与毕业衔接'];
const versions=[['V1.2','当前版本','成长数据更新','2026-08-12'],['V1.1','历史版本','根据个人实际情况调整','2026-07-18'],['V1.0','历史版本','首次生成','2026-03-12']];
function head(title,sub,actions=''){return `<div class="plan-page-head"><div><h1>${title}</h1><p>${sub}</p></div><div>${actions}</div></div>`}
function goto(v,extra=''){return `data-plan-pc-view="${v}" ${extra}`}
function planHome(){return head('AI生涯规划','查看、完善并持续更新你的正式规划报告。',`<button class="primary" ${goto('create')}>生成新的规划书</button>`)+`<section class="plan-hero"><div><span>AI CAREER PLAN</span><h2>AI帮你规划<br>大学生涯成长路径</h2><p>基于你的画像、成长经历与学校资源，形成可以持续校准的发展报告。</p></div><div class="plan-hero-mark">AI</div></section><button class="plan-change-banner" ${goto('update')}><span>成长数据有新变化</span><b>职业发展方向分析需要更新</b><small>新的职业兴趣测评会让方向建议更贴近你现在的兴趣和偏好。</small><i>查看变化 →</i></button><div class="plan-record-layout"><section><div class="plan-section-title"><h2>当前主规划</h2><span>仅一份</span></div><article class="plan-book-card main" ${goto('report')}><div class="book-cover"><small>YUN CAREER</small><b>AI 生涯<br>规划书</b><em>2026—2029</em></div><div><span class="plan-chip">主规划 · 探索型规划书</span><h2>大学生涯探索与成长规划</h2><p>${state.student.grade} · ${state.student.stage} · V1.2</p><small>本阶段重点：认识自我、体验职业，形成1—2个重点探索方向</small><time>更新于 2026-08-12</time></div><i>›</i></article></section><aside><div class="plan-section-title"><h2>其他规划</h2><span>1份</span></div><article class="other-plan"><b>数字媒体职业方向规划</b><p>方向型规划书 · V1.0</p><button data-set-main>设置为主规划</button></article></aside></div>`}
function createPage(){const t=types[planType];let config=planType==='exploration'?`<h3>专业相关探索方向</h3><div class="direction-options"><button class="selected">数字内容与交互设计</button><button>互联网产品与运营</button><button>数字媒体技术应用</button></div><p class="plan-note">无需确认唯一岗位，可直接生成探索型规划书。</p>`:planType==='direction'?`<h3>选择发展路径</h3><div class="direction-options path"><button class="selected">直接就业</button><button>基层就业</button><button>升学</button><button>参军入伍</button><button>自主创业</button></div><h3>当前比较方向</h3><p>数字产品、交互设计与内容运营方向。</p>`:`<h3>确认唯一目标岗位</h3><div class="job-search">搜索完整岗位库</div><article class="job-option selected"><b>交互设计师</b><span>支持 AI 模拟面试</span><p>负责产品交互流程、原型与体验优化。</p></article>`;return head('生成新的规划书','选择与你当前状态匹配的规划类型。',`<button ${goto('home')}>返回规划首页</button>`)+`<section class="plan-create-shell"><div class="plan-type-grid">${Object.entries(types).map(([k,x])=>`<button class="${planType===k?'active':''}" data-plan-type="${k}"><span>${x.tip}</span><h2>${x.name}</h2><p>${x.desc}</p><i>${planType===k?'已选择':'选择此类型'}</i></button>`).join('')}</div><div class="plan-create-config"><div><small>当前规划类型</small><h2>${t.name}</h2><p>${t.desc}</p><div class="readiness"><span>数据准备度</span><b>78%</b><i><em></em></i><small>缺少职业价值观测评，将使用低数据模式生成初步结论。</small></div></div><div class="config-content">${config}<button class="primary generate-plan" ${goto('generating')}>${planType==='exploration'?'生成初步规划书':'生成规划书'}</button></div></div></section>`}
function generating(){return `<section class="plan-generating"><div>AI</div><span>AI CAREER PLAN</span><h1>正在形成你的规划书</h1><p>分析生涯画像，判断发展阶段，匹配方向与学校资源。</p><ol><li class="done">分析画像</li><li class="active">生成路线</li><li>形成报告</li></ol></section>`}
function reportSection(i,title,body){return `<section id="plan-chapter-${i}" class="plan-report-section"><header><span>${String(i).padStart(2,'0')}</span><h2>${title}</h2>${[4,6,7,8].includes(i)?`<button ${goto('correction')} data-feedback-title="${title}">校正建议</button>`:''}</header>${body}</section>`}
function report(){const dims=state.careerArchive.dimensions;return head('AI生涯规划书',`大学生涯探索与成长规划 · ${version}`,`<button ${goto('correction')}>校对与完善</button><button ${goto('versions')}>版本记录</button><button class="primary" data-plan-export>导出PDF</button>`)+`<div class="plan-report-layout"><aside class="plan-report-toc"><b>规划书目录</b>${chapters.map((x,i)=>`<a href="#plan-chapter-${i+1}"><span>${String(i+1).padStart(2,'0')}</span>${x}</a>`).join('')}</aside><article class="plan-report-paper"><div class="plan-report-cover"><small>云生涯 · AI CAREER PLAN</small><span>探索型规划书</span><h1>AI 生涯<br>规划书</h1><p>面向成长的大学阶段发展规划</p><dl><div><dt>学生</dt><dd>${state.student.name}</dd></div><div><dt>专业</dt><dd>${state.student.major}</dd></div><div><dt>当前阶段</dt><dd>${state.student.stage}</dd></div><div><dt>当前版本</dt><dd>${version}</dd></div></dl></div>${reportSection(1,chapters[0],`<div class="summary-box"><div><small>当前阶段</small><b>${state.student.stage}</b></div><div><small>数据完整度</small><b>${state.student.archiveCompleteness}%</b></div><div><small>本阶段核心</small><b>认识自我、体验职业，形成1—2个重点探索方向</b></div></div><p class="report-warning">当前为低数据探索版本，不输出精确岗位差距结论。</p>`)}${reportSection(2,chapters[1],`<div class="portrait-summary"><div><b>潜力待发掘</b><span>能力关键词</span></div><div><b>专业学习能力</b><span>当前优势</span></div><div><b>就业实践能力</b><span>待提升</span></div></div>`)}${reportSection(3,chapters[2],`<p>结合职业性格、职业倾向、职业锚和职业兴趣测评，当前处于开放探索阶段，适合通过真实课程和体验进一步验证兴趣。</p>`)}${reportSection(4,chapters[3],`<div class="report-directions"><article><b>数字内容与交互设计</b><p>与专业学习能力和视觉表达兴趣关联较强。</p></article><article><b>互联网产品与运营</b><p>建议通过职业人物访谈验证工作内容偏好。</p></article><article><b>数字媒体技术应用</b><p>可结合课程项目继续积累实践证据。</p></article></div>`)}${reportSection(5,chapters[4],`<div class="six-stage-path">${stages.map((x,i)=>`<div class="${i===1?'focus':''}"><span>${i+1}</span><b>第${i+1}阶段</b><p>${x}</p>${i===1?'<em>建议优先关注</em>':''}</div>`).join('')}</div>`)}${reportSection(6,chapters[5],`<article class="recommend-row"><b>继续学习职业世界探索方法</b><p>建立职业信息搜集与比较方法。</p><button data-page="course">进入线上课</button></article>`)}${reportSection(7,chapters[6],`<article class="recommend-row"><b>参加数字产品职业沙龙</b><p>通过行业分享了解真实工作场景。</p><button data-page="activity">进入生涯活动</button></article>`)}${reportSection(8,chapters[7],`<article class="recommend-row"><b>补充就业实践能力</b><p>通过体验周、活动或实训积累真实场景经验。</p><button data-page="training">进入实训辅导</button></article>`)}${reportSection(9,chapters[8],`<article class="recommend-row"><b>数字媒体技术职业探索资源</b><p>推荐内容仅来自学校已配置的课程和专业认知。</p><button data-page="major">查看专业认知</button></article>`)}</article></div>`}
function correction(){return head('校对与完善','通过反馈实际情况校正AI建议，不直接改写规划正文。',`<button ${goto('report')}>返回规划书</button>`)+`<section class="correction-page"><h2>${feedback||'选择需要校正的建议'}</h2><p>以下四类建议可反馈：职业发展方向、学业提升、实践经历、能力短板提升。</p><div class="correction-choices"><button data-correction-choice="done" class="${correctionChoice==='done'?'active':''}"><b>已完成 / 已经掌握</b><span>无需填写说明，后续避免重复推荐。</span></button><button data-correction-choice="mismatch" class="${correctionChoice==='mismatch'?'active':''}"><b>与我的实际情况不符</b><span>需要补充不超过100字的实际情况。</span></button></div>${correctionChoice==='mismatch'?'<textarea maxlength="100" placeholder="请说明你的实际情况"></textarea>':''}<button class="primary" ${goto('correction-preview')}>生成调整预览</button></section>`}
function correctionPreview(){return head('校正结果预览','采用前不会修改当前规划。')+`<section class="preview-grid"><article><small>原建议</small><h3>继续补充数字媒体行业认知</h3><p>通过课程和活动了解代表职业方向。</p></article><article><small>学生反馈</small><h3>${correctionChoice==='done'?'已经完成相关学习':'与当前实际情况不符'}</h3><p>反馈只用于本次AI调整，不写入正式报告正文。</p></article><article class="after"><small>AI调整后建议</small><h3>转向真实项目与职业体验验证</h3><p>减少重复认知内容，优先关联体验周和实训资源。</p></article></section><div class="decision-actions"><button ${goto('report')}>保留原规划</button><button class="primary" data-apply-correction>采用调整方案</button></div>`}
function updatePage(){return head('成长数据更新','只展示受到实质影响的规划内容。',`<button ${goto('home')}>暂不采用</button>`)+`<section class="update-page"><div class="update-intro"><b>检测到新的成长数据</b><p>职业兴趣测评已形成正式结果。</p></div><article><h2>职业发展方向分析需要更新</h2><p>新的测评结果会让职业方向建议更贴近你现在的兴趣和偏好。</p><small>更新后将优化：方向说明、相关资源推荐。</small></article><article><h2>能力短板与提升建议需要更新</h2><p>新结果补充了职业活动偏好，可减少不相关的提升建议。</p><small>更新后将优化：能力建议、实践资源。</small></article><button class="primary" ${goto('update-result')}>采用新数据并更新规划</button></section>`}
function updateResult(){return `<section class="plan-result"><span>✓</span><h1>规划已完成同步</h1><p>职业发展方向分析和能力提升建议已更新，并生成新版本V1.3。</p><div><button ${goto('report')} data-version="V1.3">查看当前规划书</button><button class="primary" ${goto('versions')}>查看版本记录</button></div></section>`}
function versionPage(){return head('版本记录','每份规划书独立维护当前版本和历史版本。',`<button ${goto('report')}>返回规划书</button>`)+`<section class="version-page">${versions.map((x,i)=>`<button class="version-item ${i===0?'current':''}" ${goto('report')} data-version="${x[0]}"><span>${x[0]}</span><div><b>${x[1]}</b><p>${x[2]} · ${x[3]}</p></div><i>查看版本快照 ›</i></button>`).join('')}</section>`}
function planPage(){return ({home:planHome,create:createPage,generating,report,correction,'correction-preview':correctionPreview,update:updatePage,'update-result':updateResult,versions:versionPage}[view]||planHome)()}
function normalizeView(v){return v==='generate'?'create':v||'home'}
function planUrl(nextView=view){const u=new URL(location.href);u.searchParams.set('page','plan');u.searchParams.set('view',nextView);if(nextView==='create')u.searchParams.set('planType',planType);else u.searchParams.delete('planType');if(nextView==='report')u.searchParams.set('version',version);else u.searchParams.delete('version');return u}
function navigate(nextView,{replace=false}={}){view=normalizeView(nextView);page='plan';history[replace?'replaceState':'pushState'](null,'',planUrl(view));render();scrollTo(0,0);if(view==='generating')setTimeout(()=>{version='V1.2';navigate('report')},900)}
const oldSimple=simple;simple=function(){return page==='plan'?planPage():oldSimple()};
const oldSync=syncUrl;syncUrl=function(){oldSync();const u=new URL(location.href);if(page==='plan'){u.searchParams.set('view',view);if(view==='create')u.searchParams.set('planType',planType);else u.searchParams.delete('planType');if(view==='report')u.searchParams.set('version',version);else u.searchParams.delete('version')}history.replaceState(null,'',u)};
const oldBind=bind;bind=function(){oldBind();document.querySelectorAll('[data-plan-view]').forEach(x=>x.onclick=()=>navigate(x.dataset.planView));document.querySelectorAll('[data-plan-pc-view]').forEach(x=>x.onclick=()=>{if(x.dataset.feedbackTitle)feedback=x.dataset.feedbackTitle;if(x.dataset.version)version=x.dataset.version;navigate(x.dataset.planPcView)});document.querySelectorAll('[data-plan-type]').forEach(x=>x.onclick=()=>{planType=x.dataset.planType;history.replaceState(null,'',planUrl('create'));render()});document.querySelectorAll('[data-correction-choice]').forEach(x=>x.onclick=()=>{correctionChoice=x.dataset.correctionChoice;render()});document.querySelectorAll('[data-apply-correction]').forEach(x=>x.onclick=()=>{version='V1.3';navigate('report')});document.querySelectorAll('[data-plan-export]').forEach(x=>x.onclick=()=>{x.textContent='PDF已生成'});document.querySelectorAll('[data-set-main]').forEach(x=>x.onclick=()=>{x.textContent='已设为主规划';x.disabled=true})};
window.addEventListener('popstate',()=>{const p=new URLSearchParams(location.search);page=p.get('page')||'home';if(page==='plan'){view=normalizeView(p.get('view'));planType=p.get('planType')||planType;version=p.get('version')||version}render();scrollTo(0,0)});
render();
})();
