(function(){
const p=new URLSearchParams(location.search);
const ui={view:p.get('view')||'list',courseId:p.get('courseId')||'',courseTab:p.get('tab')||'detail',courseKeyword:p.get('keyword')||'',videoId:p.get('videoId')||'',majorId:p.get('majorId')||'',majorTab:p.get('tab')||'intro',majorCategory:p.get('category')||'哲学',majorKeyword:p.get('keyword')||'',notice:''};
const courseSections=['礼仪系列','简历系列','面试技巧系列'];
const courses=[
 {key:'value-lesson-5',courseId:'126',section:'礼仪系列',views:47,title:'第五课 生涯启蒙课——认知自我，价值观密码',series:'职业生涯规划系列课程',author:'西北农林科技大学-冯小龙',evidencedDetail:true},
 {key:'ability-lesson-6',section:'礼仪系列',views:9,title:'第六课 生涯启蒙课——认知自我，能力密码',series:'职业生涯规划系列课程',author:'西北农林科技大学-冯小龙'},
 {key:'career-intro-lesson-1',section:'礼仪系列',views:64,title:'第一课 生涯基础课——课程导论，生涯密码',series:'职业生涯规划系列课程',author:'西北农林科技大学-冯小龙'},
 {key:'resume-career-intro',section:'简历系列',views:64,title:'第一课 生涯基础课——课程导论，生涯密码',series:'职业生涯规划系列课程',author:'西北农林科技大学-冯小龙'},
 {key:'resume-explore-lesson-2',section:'简历系列',views:23,title:'第二课 生涯基础课——外部探索，职业密码',series:'职业生涯规划系列课程',author:'西北农林科技大学-冯小龙'},
 {key:'star-interview-lesson-10',section:'面试技巧系列',views:8,title:'第十课，面试中如何运用“Star法则”在竞争中取胜',series:'生涯规划之就业指导系列专题课程',author:'云研科技——云小研'},
 {key:'interview-question-lesson-11',section:'面试技巧系列',views:6,title:'第十一课，面试官提出的“套路”问题你是否能够接住？',series:'生涯规划之就业指导系列专题课程',author:'云研科技——云小研'}
];
const videos=[['office-01','@办公室礼仪01',7,1],['office-06','@办公室礼仪06',3,1],['office-05','@办公室礼仪05',6,1],['office-09','@办公室礼仪09',2,0],['office-07','@办公室礼仪07',1,0],['office-02','@办公室礼仪02',2,0],['office-04','@办公室礼仪04',0,1],['office-08','@办公室礼仪08',2,0],['office-10','@办公室礼仪10~',2,0]].map((x,i)=>({id:x[0],title:x[1],views:x[2],likes:x[3],tone:i%4}));
const majorCategories=[{id:'哲学',children:[{id:'哲学类',majors:['哲学','逻辑学','宗教学','伦理学']}]},...['经济学','法学','教育学','文学','历史学','理学','工学','农学','医学','管理学','艺术学'].map(id=>({id,children:[]}))];
const majorDetails={
 '哲学':{summary:'哲学专业是一门研究和探索人类认知、价值、存在、认识论、伦理学、美学等基本问题的学科。',intro:['一、专业概述：哲学专业融合历史学、文学、社会学、心理学等多学科知识，旨在培养具备批判性思维、逻辑分析和道德判断能力的人才。','专业包含逻辑学、伦理学、美学、认识论、政治哲学等细分方向。','学习中应培养批判性思维和独立思考能力，注重跨学科知识学习，并练习写作和表达能力。','毕业生应具备扎实的哲学理论基础和较强的逻辑分析能力，能够独立进行哲学研究和论文写作。','毕业生可从事教育、科研、管理、咨询等工作，也可在政府机构、非营利组织、新闻媒体和企业就业。'],courses:['中华文明史','西方哲学史','逻辑学','伦理学','认识论','政治哲学','美学','现代西方哲学'],jobs:[['教育与科研','从事哲学教学、研究和学术支持'],['战略规划','运用批判性思维参与组织战略分析'],['法律合规','参与伦理审查、政策分析与合规工作']],industries:['教育与科研','政府与公共服务','新闻媒体','企业战略与咨询']},
 '机电一体化技术':{college:'智能制造学院',category:'装备制造大类 · 自动化类',degree:'专科',years:'三年',summary:'面向智能制造生产、建设、服务和管理一线，培养掌握机械、电气、控制与数字化技术的高素质技术技能人才。',intro:['机电一体化技术融合机械制造、电工电子、自动控制、工业网络等知识。学生将学习设备安装调试、故障诊断、自动化生产线运行维护和数字化改造。','专业强调真实项目训练，通过工业机器人工作站、PLC控制、智能产线等实训形成解决复杂现场问题的能力。'],courses:['机械制图与CAD','电工电子技术','PLC应用技术','工业机器人技术','传感器与检测技术','自动化生产线安装与调试'],jobs:[['机电设备技术员','负责设备安装、点检、维护与技术改造'],['自动化生产线运维工程师','负责PLC、传感器和产线运行维护'],['工业机器人系统操作员','负责机器人工作站编程、调试与维护'],['智能制造售后工程师','为客户提供设备交付、培训和技术支持']],industries:['智能装备制造','新能源汽车','工业自动化','电子信息制造']}
};
const courseState=JSON.parse(localStorage.getItem('max-pc-course-state')||'{"owned":false,"collected":false,"favored":false,"progress":0}');
const videoLikes=JSON.parse(localStorage.getItem('max-pc-video-likes')||'{}');
function saveCourse(){localStorage.setItem('max-pc-course-state',JSON.stringify(courseState))}
function titleHead(title,desc,back){return `<div class="learning-page-head"><div>${back?'<button data-learning-back>‹ 返回列表</button>':''}<h1>${title}</h1><p>${desc}</p></div></div>`}
function notice(){return ui.notice?`<div class="learning-toast" role="status">${ui.notice}</div>`:''}
function courseCard(c){return `<article class="max-course-card" data-course-open="${c.courseId||c.key}"><div class="max-course-cover ${c.section==='面试技巧系列'?'empty':''}">${c.section==='面试技巧系列'?'<span>▧</span>':`<img src="assets/online-course/course-cover.png" alt="${c.title}封面">`}<em>◉ ${c.views}</em></div><div class="max-course-copy"><h3>${c.title}</h3><p>${c.series}</p><small>${c.author}</small></div></article>`}
function courseList(){const q=ui.courseKeyword.trim();const sections=courseSections.map(s=>({title:s,items:courses.filter(c=>c.section===s&&(!q||c.title.includes(q)||c.author.includes(q)))})).filter(x=>x.items.length);return titleHead('线上课','查看云生涯Max现有课程内容与学习记录')+`<section class="learning-shell"><label class="learning-search"><span>⌕</span><input data-course-search value="${ui.courseKeyword}" placeholder="搜索"></label>${sections.length?sections.map(s=>`<section class="max-course-section"><header><h2>${s.title}</h2><span>更多</span></header><div class="max-course-grid">${s.items.map(courseCard).join('')}</div></section>`).join(''):'<div class="learning-empty"><b>暂无相关课程</b><p>请修改搜索关键词后重试。</p></div>'}</section>${notice()}`}
function courseDetail(){const c=courses.find(x=>x.courseId===ui.courseId)||courses[0];return titleHead('线上课','复用Max已完成实机取证的课程详情',true)+`<section class="max-course-detail"><div class="course-detail-hero"><img src="assets/online-course/course-hero.png" alt="课程主视觉"></div><div class="course-detail-meta"><span>1970-01-01 08:00 | ${c.views} 次浏览</span><div><button class="${courseState.favored?'active':''}" data-course-favor>♧ 点赞</button><button class="${courseState.collected?'active':''}" data-course-collect>★ 收藏</button></div></div><div class="learning-tabs"><button class="${ui.courseTab==='detail'?'active':''}" data-course-tab="detail">详情</button><button class="${ui.courseTab==='chapters'?'active':''}" data-course-tab="chapters">章节</button></div>${ui.courseTab==='detail'?`<div class="course-detail-body"><img src="assets/online-course/course-detail.png" alt="课程详情"></div>`:`<div class="course-chapters"><header><span>学习进度</span><b>${courseState.progress}%</b></header><div class="progress-line"><i style="width:${courseState.progress}%"></i></div><button data-course-study><em>1</em><span><b>${c.title}</b><small>${courseState.progress?'继续学习':'开始学习'}</small></span><strong>›</strong></button></div>`}<div class="course-action-bar">${courseState.owned?`<button class="primary" data-course-tab="chapters">${courseState.progress?'继续学习':'开始学习'}</button>`:'<button class="primary" data-course-claim>立即领取</button>'}</div></section>${notice()}`}
function videoStage(v,detail=false){return `<div class="max-video-stage tone-${v.tone} ${detail?'detail':''}"><div class="office-window"></div><div class="office-desk"></div><div class="office-person"></div><button class="video-play" data-video-play="${v.id}">▶</button></div>`}
function videoList(){return titleHead('微视频','查看云生涯Max现有办公室礼仪微视频')+`<section class="max-video-grid">${videos.map(v=>`<article class="max-video-card">${videoStage(v)}<div><h3>${v.title}</h3><p><span>◉ ${v.views}</span><button data-video-like="${v.id}">♡ ${v.likes+(videoLikes[v.id]?1:0)}</button><button data-video-share="${v.id}">↗ 分享</button></p></div></article>`).join('')}</section>${notice()}`}
function videoDetail(){const v=videos.find(x=>x.id===ui.videoId)||videos[0];return titleHead('微视频','复用Max视频详情与操作状态',true)+`<section class="max-video-detail">${videoStage(v,true)}<div class="video-detail-copy"><h1>${v.title.replace('@','')}</h1><p>${v.views||6} 人观看</p><div><button data-video-like="${v.id}">♡ ${v.likes+(videoLikes[v.id]?1:0)}</button><button>☆ 1</button><button data-video-share="${v.id}">↗ 1</button><button>0</button><button>0</button></div></div></section>${notice()}`}
function allMajors(){return majorCategories.flatMap(c=>c.children.flatMap(g=>g.majors.map(name=>({name,category:c.id,group:g.id}))))}
function majorList(){const q=ui.majorKeyword.trim();const active=majorCategories.find(x=>x.id===ui.majorCategory)||majorCategories[0];const rows=q?allMajors().filter(x=>x.name.includes(q)):active.children.flatMap(g=>g.majors.map(name=>({name,category:active.id,group:g.id})));const content=rows.length?`<div class="major-grid">${rows.map(m=>`<button data-major-open="${m.name}"><span>专</span><b>${m.name}</b><small>${m.group}</small><i>查看详情 ›</i></button>`).join('')}</div>`:`<div class="learning-empty"><b>暂无专业数据</b><p>${q?'没有匹配的职位，修改搜索条件再试试':'该门类暂无更多数据'}</p></div>`;return titleHead('专业认知','查看云生涯Max现有专业门类与专业介绍')+`<section class="major-shell"><label class="learning-search"><span>⌕</span><input data-major-search value="${ui.majorKeyword}" placeholder="输入专业名称搜索"></label><div class="major-layout ${q?'searching':''}"><aside>${majorCategories.map(c=>`<button class="${c.id===ui.majorCategory?'active':''}" data-major-category="${c.id}">${c.id}</button>`).join('')}</aside><main><header><small>${q?'跨门类搜索结果':active.id}</small><h2>${q?`“${q}”相关专业`:(active.children[0]?.id||'专业类')}</h2></header>${content}</main></div></section>`}
function majorDetail(){const name=ui.majorId||'哲学',d=majorDetails[name]||majorDetails['哲学'];return titleHead('专业介绍','复用Max专业介绍与符合岗位页面',true)+`<section class="major-detail"><header><div><small>${d.category||'哲学类'} ${d.degree?`· ${d.degree} · ${d.years}`:''}</small><h1>${name}</h1><p>${d.summary}</p></div><button data-major-video><span>数字人</span><b>▶ 专业介绍</b><small>点击播放 / 暂停</small></button></header><div class="learning-tabs"><button class="${ui.majorTab==='intro'?'active':''}" data-major-tab="intro">专业介绍</button><button class="${ui.majorTab==='jobs'?'active':''}" data-major-tab="jobs">符合岗位</button></div>${ui.majorTab==='intro'?`<div class="major-intro"><section><h2>专业概述</h2>${d.intro.map(x=>`<p>${x}</p>`).join('')}</section><aside><h2>核心课程</h2>${d.courses.map(x=>`<span>${x}</span>`).join('')}</aside></div>`:`<div class="major-jobs"><section><h2>符合岗位</h2>${d.jobs.map(x=>`<article><span>岗</span><div><h3>${x[0]}</h3><p>${x[1]}</p></div></article>`).join('')}</section><aside><h2>主要就业行业</h2>${d.industries.map(x=>`<span>${x}</span>`).join('')}</aside></div>`}</section>${notice()}`}
function learningPage(){if(page==='course')return ui.view==='detail'?courseDetail():courseList();if(page==='video')return ui.view==='detail'?videoDetail():videoList();return ui.view==='detail'?majorDetail():majorList()}
const oldSync=syncUrl;syncUrl=function(){oldSync();const u=new URL(location.href),keys=['view','courseId','videoId','majorId','category','keyword'];if(['course','video','major'].includes(page)){u.searchParams.set('view',ui.view);keys.slice(1).forEach(k=>u.searchParams.delete(k));u.searchParams.delete('tab');if(page==='course'){ui.courseId&&u.searchParams.set('courseId',ui.courseId);ui.courseKeyword&&u.searchParams.set('keyword',ui.courseKeyword);if(ui.view==='detail')u.searchParams.set('tab',ui.courseTab)}if(page==='video'&&ui.videoId)u.searchParams.set('videoId',ui.videoId);if(page==='major'){ui.majorCategory&&u.searchParams.set('category',ui.majorCategory);ui.majorKeyword&&u.searchParams.set('keyword',ui.majorKeyword);ui.majorId&&u.searchParams.set('majorId',ui.majorId);if(ui.view==='detail')u.searchParams.set('tab',ui.majorTab)}}else{keys.forEach(k=>u.searchParams.delete(k));u.searchParams.delete('tab')}history.replaceState(null,'',u)};
const oldBind=bind;bind=function(){oldBind();document.querySelector('[data-learning-back]')?.addEventListener('click',()=>{ui.view='list';ui.notice='';render();scrollTo(0,0)});document.querySelector('[data-course-search]')?.addEventListener('input',e=>{ui.courseKeyword=e.target.value;render();document.querySelector('[data-course-search]')?.focus()});document.querySelectorAll('[data-course-open]').forEach(x=>x.onclick=()=>{const c=courses.find(i=>(i.courseId||i.key)===x.dataset.courseOpen);if(!c.evidencedDetail){ui.notice='该课程详情尚未完成 Max 实机取证';render();return}ui.courseId=c.courseId;ui.view='detail';ui.courseTab='detail';ui.notice='';render();scrollTo(0,0)});document.querySelectorAll('[data-course-tab]').forEach(x=>x.onclick=()=>{if(x.dataset.courseTab==='chapters'&&!courseState.owned){ui.notice='请先领取课程';render();return}ui.courseTab=x.dataset.courseTab;ui.notice='';render()});document.querySelector('[data-course-claim]')?.addEventListener('click',()=>{courseState.owned=true;saveCourse();ui.notice='领取成功';render()});document.querySelector('[data-course-favor]')?.addEventListener('click',()=>{courseState.favored=!courseState.favored;saveCourse();render()});document.querySelector('[data-course-collect]')?.addEventListener('click',()=>{courseState.collected=!courseState.collected;saveCourse();render()});document.querySelector('[data-course-study]')?.addEventListener('click',()=>{courseState.progress=courseState.progress?100:35;saveCourse();ui.notice=courseState.progress===100?'学习完成':'已保存学习进度';render()});document.querySelectorAll('[data-video-play]').forEach(x=>x.onclick=()=>{if(ui.view==='detail'){x.closest('.max-video-stage').classList.toggle('playing');x.textContent=x.closest('.max-video-stage').classList.contains('playing')?'❚❚':'▶'}else{ui.videoId=x.dataset.videoPlay;ui.view='detail';ui.notice='';render();scrollTo(0,0)}});document.querySelectorAll('[data-video-like]').forEach(x=>x.onclick=()=>{videoLikes[x.dataset.videoLike]=!videoLikes[x.dataset.videoLike];localStorage.setItem('max-pc-video-likes',JSON.stringify(videoLikes));render()});document.querySelectorAll('[data-video-share]').forEach(x=>x.onclick=()=>{ui.notice='分享正在按 Max 实机取证';render()});document.querySelector('[data-major-search]')?.addEventListener('input',e=>{ui.majorKeyword=e.target.value;render();document.querySelector('[data-major-search]')?.focus()});document.querySelectorAll('[data-major-category]').forEach(x=>x.onclick=()=>{ui.majorCategory=x.dataset.majorCategory;ui.majorKeyword='';render()});document.querySelectorAll('[data-major-open]').forEach(x=>x.onclick=()=>{ui.majorId=x.dataset.majorOpen;ui.view='detail';ui.majorTab='intro';ui.notice='';render();scrollTo(0,0)});document.querySelectorAll('[data-major-tab]').forEach(x=>x.onclick=()=>{ui.majorTab=x.dataset.majorTab;render()});document.querySelector('[data-major-video]')?.addEventListener('click',e=>{e.currentTarget.classList.toggle('playing');ui.notice=e.currentTarget.classList.contains('playing')?'开始播放':'已暂停';render()})};
const oldRender=render;render=function(){if(['course','video','major'].includes(page)){app.innerHTML=shell(learningPage());bind();syncUrl();return}oldRender()};render();
})();
